import { describe, expect, it } from 'vitest';
import { useGameStore } from '../src/store/gameStore';
import {
  KATRAIN_SGF_INTERNAL_COMMENTS_MARKER,
  buildKaTrainSgfComment,
  extractKaTrainUserNoteFromSgfComment,
  generateSgfFromTree,
  parseSgf,
} from '../src/utils/sgf';

/**
 * The app writes its own text into `C` alongside the user's note -- "SGF
 * generated by WebKatrain", and the marks legend when that is on -- and tells
 * the two apart on the way back in with an invisible sentinel
 * (U+3164 U+200B). Nothing tested that, and getting it wrong is silent either
 * way: the note is lost, or the app's own boilerplate becomes the note and
 * grows by one line every save.
 */
describe('the app\'s own comments and the user\'s note', () => {
  const internal = (text: string) => `${text}${KATRAIN_SGF_INTERNAL_COMMENTS_MARKER}`;

  it('hands back only the user\'s half', () => {
    const comment = buildKaTrainSgfComment({
      note: 'my own words',
      internalSegments: [internal('SGF generated by WebKatrain')],
    });
    expect(comment).toContain('my own words');
    expect(comment).toContain('WebKatrain');
    expect(extractKaTrainUserNoteFromSgfComment([comment!])).toBe('my own words');
  });

  it('reads no note at all when only the app wrote something', () => {
    const comment = buildKaTrainSgfComment({ internalSegments: [internal('SGF generated by WebKatrain')] });
    expect(comment).toBeTruthy();
    // Otherwise every exported game comes back with boilerplate as its note.
    expect(extractKaTrainUserNoteFromSgfComment([comment!])).toBe('');
  });

  it('writes nothing when there is nothing to say', () => {
    expect(buildKaTrainSgfComment({})).toBeNull();
    expect(extractKaTrainUserNoteFromSgfComment(undefined)).toBe('');
    expect(extractKaTrainUserNoteFromSgfComment([])).toBe('');
  });

  /** Round trips through the store, which is what turns a file into nodes. */
  const exportAfterLoading = (sgf: string): string => {
    useGameStore.getState().loadGame(parseSgf(sgf));
    return generateSgfFromTree(useGameStore.getState().rootNode);
  };

  it('keeps the user\'s root note across export and re-import', () => {
    const once = exportAfterLoading('(;GM[1]FF[4]SZ[9]C[what I thought before move one];B[dd];W[ff])');
    expect(once).toContain('what I thought before move one');
    useGameStore.getState().loadGame(parseSgf(once));
    expect(useGameStore.getState().rootNode.note ?? '').toBe('what I thought before move one');
  });

  it('never turns its own boilerplate into the user\'s note', () => {
    const once = exportAfterLoading('(;GM[1]FF[4]SZ[9];B[dd])');
    useGameStore.getState().loadGame(parseSgf(once));
    expect(useGameStore.getState().rootNode.note ?? '').toBe('');
  });

  it('does not accumulate its own boilerplate over repeated saves', () => {
    // Export -> import -> export. The app's line must appear once, not twice.
    const once = exportAfterLoading('(;GM[1]FF[4]SZ[9];B[dd])');
    const twice = exportAfterLoading(once);
    const thrice = exportAfterLoading(twice);
    const count = (text: string) => text.split('SGF generated by WebKatrain').length - 1;
    expect([count(once), count(twice), count(thrice)]).toEqual([1, 1, 1]);
  });
});
